apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # Your app title
  APP_TITLE: "Final Project - Group 9"

  # S3 bucket and object key for Phase 7 (mountain image)
  S3_BUCKET: "group9-project-images"
  S3_IMAGE_KEY: "ocean.jpg"
